CREATE TABLE `mission_study_materials` (
	`mission_id` integer PRIMARY KEY NOT NULL,
	`title` text NOT NULL,
	`introduction` text NOT NULL,
	`explanation` text NOT NULL,
	`example_code` text NOT NULL,
	`example_explanation` text NOT NULL,
	`key_points_json` text DEFAULT '[]' NOT NULL,
	`common_mistakes_json` text DEFAULT '[]' NOT NULL,
	`references_json` text DEFAULT '[]' NOT NULL,
	FOREIGN KEY (`mission_id`) REFERENCES `missions`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
INSERT INTO `mission_study_materials` (`mission_id`,`title`,`introduction`,`explanation`,`example_code`,`example_explanation`,`key_points_json`,`common_mistakes_json`,`references_json`) VALUES
(1,'Funções e retorno','Uma função recebe dados, executa uma tarefa e pode devolver um resultado.','Parâmetros são os valores de entrada. A instrução return entrega o resultado para quem chamou a função.','function criarApelido(nome) {\n  return "Herói " + nome;\n}','O nome entra pelo parâmetro e a nova string sai pelo return.','["Use exatamente os parâmetros declarados","return encerra a função e devolve um valor"]','["Usar console.log no lugar de return","Ignorar o parâmetro recebido"]','[]'),
(2,'Decisões com comparações','Comparações produzem true ou false e permitem decidir o que o programa deve fazer.','Os operadores >=, <=, > e < comparam números. O resultado da comparação já é um valor booleano.','function temDesconto(pontos) {\n  return pontos >= 10;\n}','A função retorna true quando pontos vale 10 ou mais.','[">= inclui o valor do limite","Não coloque true e false entre aspas"]','["Usar > quando o limite também deve valer","Retornar texto em vez de booleano"]','[]'),
(3,'Percorrendo arrays','Arrays guardam vários valores em ordem. Uma repetição permite visitar cada item.','Crie um acumulador antes do laço, atualize-o para cada item e retorne o resultado ao final.','function totalizarPrecos(precos) {\n  let total = 0;\n  for (const preco of precos) total += preco;\n  return total;\n}','O for...of percorre cada preço e o acumulador guarda o total.','["Inicialize o acumulador","Retorne depois de percorrer todos os itens"]','["Retornar dentro do laço","Alterar o array recebido sem necessidade"]','[]'),
(4,'Transformando um número','Operadores aritméticos criam novos valores a partir de uma entrada.','Multiplicar uma entrada por uma constante é uma transformação simples e não exige alterar o parâmetro.','function triplo(valor) {\n  return valor * 3;\n}','A função usa o valor recebido e devolve outro número.','["Use o parâmetro recebido","Retorne o resultado da expressão"]','["Fixar um número específico","Esquecer o return"]','[]'),
(5,'Filtrando coleções','Filtrar significa criar uma coleção somente com os itens que atendem a uma condição.','O método filter testa cada item e mantém aqueles para os quais a função retorna true.','function positivos(valores) {\n  return valores.filter(valor => valor > 0);\n}','Cada valor é comparado com zero; apenas os positivos entram no novo array.','["filter devolve um novo array","A condição precisa produzir true ou false"]','["Retornar o valor em vez da condição","Modificar o array original"]','[]'),
(6,'Consultando uma tabela','SELECT escolhe as colunas e FROM informa de qual tabela os dados vêm.','Use * quando precisar visualizar todas as colunas ou liste os nomes separados por vírgula.','SELECT *\nFROM CLIENTES;','A consulta retorna todas as colunas e linhas da tabela de exemplo CLIENTES.','["SELECT vem antes de FROM","O nome da tabela deve existir"]','["Omitir FROM","Inventar nomes de colunas"]','[]'),
(7,'Filtrando linhas com WHERE','WHERE mantém somente as linhas cuja condição é verdadeira.','Textos em SQL usam aspas simples e a comparação de igualdade usa =.','SELECT *\nFROM CLIENTES\nWHERE STATUS = ''A'';','Somente clientes com STATUS igual a A aparecem.','["WHERE vem depois de FROM","Valores de texto usam aspas simples"]','["Usar ==","Comparar texto sem aspas"]','[]'),
(8,'Ordenando resultados','ORDER BY organiza as linhas por uma ou mais colunas.','ASC ordena do menor para o maior; DESC faz o caminho inverso.','SELECT *\nFROM CLIENTES\nORDER BY NOME ASC;','Os clientes são apresentados em ordem crescente de nome.','["ORDER BY vem após FROM e WHERE","ASC significa crescente"]','["Ordenar por coluna inexistente","Confundir ASC com DESC"]','[]'),
(9,'Consultando uma faixa','BETWEEN verifica valores dentro de dois limites e inclui os extremos.','A expressão coluna BETWEEN mínimo AND máximo é útil para preços, datas e quantidades.','SELECT *\nFROM PEDIDOS\nWHERE TOTAL BETWEEN 100 AND 300;','A consulta inclui pedidos de 100, de 300 e os valores entre eles.','["BETWEEN inclui os limites","Informe primeiro o menor valor"]','["Inverter mínimo e máximo","Esquecer o AND"]','[]'),
(10,'Buscando padrões de texto','LIKE compara texto com um padrão. O curinga % representa qualquer sequência de caracteres.','Coloque % antes e depois do termo quando ele puder aparecer em qualquer parte do texto.','SELECT *\nFROM CLIENTES\nWHERE NOME LIKE ''%Silva%'';','O padrão encontra nomes que contenham Silva em qualquer posição.','["% pode representar vários caracteres","O padrão é um texto entre aspas"]','["Usar = com curingas","Esquecer um dos % quando a busca é contém"]','[]'),
(11,'Comparando com uma lista','IN testa se um valor pertence a uma lista de opções.','Separe as opções por vírgula dentro de parênteses.','SELECT *\nFROM PEDIDOS\nWHERE ID IN (2, 5, 8);','A consulta mantém somente os pedidos com um dos três identificadores.','["As opções ficam entre parênteses","Separe valores por vírgula"]','["Omitir os parênteses","Usar AND entre valores alternativos"]','[]'),
(12,'Títulos e parágrafos','Uma página clara começa com uma hierarquia de conteúdo fácil de entender.','Use h1 para o título principal e p para um bloco de texto. Os dois elementos devem ficar dentro da área principal da página.','<main>\n  <h1>Portal da Guilda</h1>\n  <p>Encontre missões para sua jornada.</p>\n</main>','O h1 apresenta o assunto principal e o parágrafo explica o propósito da página.','["Use apenas um título principal por contexto","Escreva o texto entre a abertura e o fechamento da tag"]','["Usar uma div sem significado para todo o conteúdo","Esquecer de fechar as tags"]','[]'),
(13,'Navegação interna','Links internos levam o visitante diretamente a uma seção da mesma página.','O href usa # seguido de um identificador. O destino precisa ter exatamente o mesmo valor no atributo id.','<nav>\n  <a href="#contato">Contato</a>\n</nav>\n<section id="contato">Fale conosco</section>','O link aponta para #contato e a seção correspondente usa id contato.','["href começa com #","O id do destino não contém #"]','["Usar valores diferentes no href e no id","Repetir o mesmo id em várias seções"]','[]'),
(14,'Listas semânticas','Listas agrupam itens relacionados e ajudam leitores e tecnologias assistivas a entender a coleção.','Use ul quando a ordem não for importante e coloque cada item dentro de li.','<ul>\n  <li>Poções</li>\n  <li>Mapas</li>\n</ul>','A ul representa a coleção; cada li representa um item separado.','["li deve ficar dentro de ul ou ol","Cada item usa sua própria tag li"]','["Escrever itens soltos sem li","Usar br para simular uma lista"]','[]'),
(15,'Formulários acessíveis','Um formulário reúne controles para receber informações do usuário.','Relacione label e input usando o mesmo valor em for e id. O type descreve o tipo de dado esperado.','<form>\n  <label for="nome">Nome</label>\n  <input id="nome" type="text">\n  <button type="submit">Enviar</button>\n</form>','O rótulo identifica o campo nome e o botão envia o formulário.','["for do label deve corresponder ao id do input","Use type submit na ação principal"]','["Usar placeholder como único rótulo","Repetir o mesmo id"]','[]'),
(16,'Cores e contraste','CSS separa a aparência da estrutura HTML. Um seletor escolhe o elemento e as propriedades definem sua aparência.','background-color controla o fundo e color controla a cor do texto.',' .aviso {\n  background-color: #1e293b;\n  color: #e2e8f0;\n}','A regra aplica um fundo escuro e um texto claro aos elementos da classe aviso.','["Propriedades ficam entre chaves","Finalize declarações com ponto e vírgula"]','["Esquecer o ponto antes da classe","Trocar color por background-color"]','[]'),
(17,'Espaço interno e externo','Espaçamento melhora a leitura e separa componentes.','padding cria espaço dentro do elemento; margin cria espaço ao redor dele.',' .painel {\n  padding: 20px;\n  margin: 12px;\n}','O conteúdo ganha respiro interno e o painel se afasta dos vizinhos.','["padding é interno","margin é externo"]','["Usar valores sem unidade","Confundir padding com margin"]','[]'),
(18,'Bordas e cantos','Bordas delimitam visualmente um componente e o raio suaviza seus cantos.','border combina espessura, estilo e cor; border-radius define o arredondamento.',' .painel {\n  border: 2px solid #475569;\n  border-radius: 8px;\n}','A regra cria um contorno sólido e cantos arredondados.','["border precisa de estilo para aparecer","Use uma unidade no raio"]','["Omitir solid","Aplicar a regra no seletor errado"]','[]'),
(19,'Layout com Flexbox','Flexbox distribui itens em uma direção e pode permitir quebra de linha.','display flex ativa o layout; gap separa os filhos; flex-wrap wrap permite que eles passem para outra linha.',' .lista {\n  display: flex;\n  gap: 12px;\n  flex-wrap: wrap;\n}','Os itens da lista ficam lado a lado, com espaço e quebra quando necessário.','["Flexbox afeta os filhos diretos","wrap evita que os itens sejam espremidos em uma única linha"]','["Aplicar display flex nos itens em vez do contêiner","Esquecer flex-wrap"]','[]');
--> statement-breakpoint
UPDATE `missions` SET `objective`='Dentro de main, crie um h1 com o texto Oficina DevDex e um parágrafo que mencione código.' WHERE `id`=12;
--> statement-breakpoint
UPDATE `missions` SET `objective`='Crie um nav com um link chamado Serviços apontando para #servicos e uma section com id servicos.' WHERE `id`=13;
--> statement-breakpoint
UPDATE `missions` SET `objective`='Crie uma lista não ordenada com ul e pelo menos três itens li.' WHERE `id`=14;
--> statement-breakpoint
UPDATE `missions` SET `objective`='Dentro de form, crie label para email, input do tipo email e botão do tipo submit.' WHERE `id`=15;
--> statement-breakpoint
PRAGMA optimize;
