"use client";

import Image from "next/image";
import { useState } from "react";
import { ArrowRight, Check, Code2, Cpu, Sparkles, Swords, Terminal, Zap } from "lucide-react";
import type { OnboardingStage } from "@/db";

type Archetype = "adventurer" | "adventuress";
type Props = { initialStage: OnboardingStage; initialPath: string; initialArchetype: Archetype; displayName: string };
const paths = [{ id: "frontend", icon: Sparkles, name: "Frontend", text: "Crie interfaces e experiências para a web.", tech: "HTML · CSS · JavaScript" }, { id: "backend", icon: Cpu, name: "Backend", text: "Construa APIs, servidores e bancos de dados.", tech: "Python · SQL · APIs" }, { id: "fullstack", icon: Code2, name: "Full Stack", text: "Conecte aplicações completas de ponta a ponta.", tech: "Frontend + Backend" }, { id: "ia", icon: Zap, name: "IA", text: "Explore aplicações inteligentes com código.", tech: "Python · APIs · Dados" }];
const characters = [{ id: "adventurer" as const, name: "HEXO", personality: "Equilíbrio e foco", image: "/characters/adventurer-male-sprite-v2.png" }, { id: "adventuress" as const, name: "LUNA", personality: "Criatividade e ideias", image: "/characters/adventuress-female-v1.png" }, { id: "adventurer" as const, name: "BYTE", personality: "Lógica e precisão", image: "/characters/adventurer-male-sprite-v2.png" }, { id: "adventuress" as const, name: "ZARA", personality: "Curiosidade e exploração", image: "/characters/adventuress-female-v1.png" }];

export function OnboardingExperience({ initialStage, initialPath, initialArchetype, displayName }: Props) {
  const [stage, setStage] = useState<OnboardingStage>(initialStage); const [path, setPath] = useState(initialPath); const [archetype, setArchetype] = useState<Archetype>(initialArchetype); const [code, setCode] = useState('console.log("Olá, DevDex!");'); const [feedback, setFeedback] = useState<string | null>(null); const [pending, setPending] = useState(false);
  async function save(next: OnboardingStage, extra: Record<string, unknown> = {}) { setPending(true); setFeedback(null); try { const response = await fetch("/api/onboarding", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ stage: next, selectedPath: path, archetype, ...extra }) }); if (!response.ok) throw new Error(); setStage(next); } catch { setFeedback("Não foi possível salvar seu avanço. Tente novamente."); } finally { setPending(false); } }
  async function tutorial() { setPending(true); setFeedback(null); try { const response = await fetch("/api/onboarding/tutorial", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ code }) }); const result = await response.json() as { ok: boolean; output?: string; message?: string }; if (!result.ok) { setFeedback(result.message ?? "Revise o código e tente outra vez."); return; } await save("reward"); } catch { setFeedback("Não foi possível executar a transmissão."); } finally { setPending(false); } }
  async function complete(skip = false) { setPending(true); try { const response = await fetch("/api/onboarding", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ complete: true, reward: !skip, selectedPath: path, archetype }) }); if (!response.ok) throw new Error(); window.location.assign("/dashboard"); } catch { setFeedback("Não foi possível concluir o onboarding."); } finally { setPending(false); } }
  const transition = (content: React.ReactNode, kicker: string) => <main className="onboarding-page"><header className="onboarding-top"><a className="brand" href="/"><span className="brand-mark">D_</span><span>DevDex</span></a><button onClick={() => complete(true)} disabled={pending}>Pular introdução</button></header><section className="onboarding-content"><span className="kicker">{kicker}</span>{content}</section></main>;
  if (stage === "intro") return transition(<><div className="onboarding-hero-art"><div className="onboarding-grid" /><Image src="/characters/adventurer-male-sprite-v2.png" alt="" width={210} height={280} priority /><span className="onboarding-scan">SINAL DEVDEX · ONLINE</span></div><h1>Entre no jogo,<br /><em>{displayName}</em>.</h1><p className="onboarding-lead">Aprenda programação. Evolua seu personagem. Domine tecnologias.</p><p className="onboarding-ambient">Todo grande desenvolvedor começou com um primeiro passo.</p><button className="button onboarding-cta" onClick={() => save("path")} disabled={pending}>Começar jornada <ArrowRight /></button></>, "PRIMEIRA TRANSMISSÃO");
  if (stage === "path") return transition(<><h1>Escolha seu caminho.</h1><p className="onboarding-lead">Cada jornada recomenda novas habilidades. Você poderá explorar qualquer tecnologia quando quiser.</p><div className="onboarding-path-grid">{paths.map(({ id, icon: Icon, name, text, tech }) => <button className={path === id ? "selected" : ""} key={id} onClick={() => setPath(id)}><Icon /><strong>{name}</strong><span>{text}</span><small>{tech}</small><Check /></button>)}</div><button className="button onboarding-cta" onClick={() => save("character")} disabled={pending}>Continuar <ArrowRight /></button></>, "ESCOLHA SEU CAMINHO");
  if (stage === "character") return transition(<><h1>Escolha seu Dev.</h1><p className="onboarding-lead">Sua personalidade é narrativa. Todos os personagens jogam com as mesmas regras.</p><div className="onboarding-character-grid">{characters.map((item) => <button className={archetype === item.id ? "selected" : ""} key={item.name} onClick={() => setArchetype(item.id)}><Image src={item.image} alt={item.name} width={100} height={125} /><strong>{item.name}</strong><span>{item.personality}</span></button>)}</div><button className="button onboarding-cta" onClick={() => save("story")} disabled={pending}>Escolher {characters.find((item) => item.id === archetype)?.name} <ArrowRight /></button></>, "SELEÇÃO DE PERSONAGEM");
  if (stage === "story") return transition(<><div className="onboarding-story"><Terminal /><span>TRANSMISSÃO 001</span><h1>A rede foi corrompida.</h1><p>Bugs começaram a se espalhar pelas regiões do código. Para restaurá-la, você vai dominar tecnologias, corrigir erros e reconstruir o conhecimento perdido.</p></div><button className="button onboarding-cta" onClick={() => save("tutorial")} disabled={pending}><Swords /> Iniciar transmissão</button></>, "CONTEXTO DA MISSÃO");
  if (stage === "tutorial") return transition(<><h1>Primeira transmissão.</h1><p className="onboarding-lead">Todo programa começa executando alguma coisa. Vamos ver isso na prática.</p><div className="onboarding-tutorial"><div className="onboarding-dialog"><Image src={characters.find((item) => item.id === archetype)?.image ?? characters[0].image} alt="" width={58} height={74} /><span>Escreva o código e execute. Erros aqui não consomem corações.</span></div><label><span><Code2 /> editor.js</span><textarea value={code} onChange={(event) => setCode(event.target.value)} spellCheck={false} aria-label="Código da primeira transmissão" /></label><div className="onboarding-console"><span>SAÍDA DO CONSOLE</span><code>{feedback?.startsWith("Não") ? "Aguardando execução..." : feedback ?? "Aguardando execução..."}</code></div></div>{feedback && !feedback.startsWith("Não") ? <p className="onboarding-feedback">{feedback}</p> : null}<button className="button onboarding-cta" onClick={tutorial} disabled={pending}>Executar código <ArrowRight /></button></>, "TUTORIAL JOGÁVEL");
  return transition(<div className="onboarding-reward"><div className="reward-icon"><Zap /></div><span className="kicker">TRANSMISSÃO CONCLUÍDA</span><h1>Muito bem.</h1><p>Você executou seu primeiro código e já pode explorar o mapa do DevDex.</p><strong>+50 XP</strong><small>Recompensa de boas-vindas · sem corações consumidos</small><button className="button onboarding-cta" onClick={() => complete()} disabled={pending}>Ir para o mapa <ArrowRight /></button></div>, "PRIMEIRA RECOMPENSA");
}
